name: Build Images
on:
  workflow_dispatch:
  repository_dispatch:
    types: [Build]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  Prepare:
    name: "Prepare"
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.releases.outputs.version}}
    timeout-minutes: 5
    steps:

      - name: "Keep only 2 ${{ github.event.client_payload.release }} releases"
        uses: Vucko130/delete-older-releases@v0.2.2
        with:
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3.4.0
        with:
          repository: armbian/os
          fetch-depth: '1'
          clean: false

      - name: Save
        id: releases
        run: |
        
          echo "${{ github.event.client_payload.version }}" > tag
          echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

          #if [[ "${{ github.event.client_payload.version }}" == null ]]; then
            echo "$(cat nightly.json | jq -r '.version')" > tag
            echo "version=$(cat nightly.json | jq -r '.version')" >> $GITHUB_OUTPUT
          #fi

  Build:

    name: "Cluster 5/6"
    needs: Prepare
    if: ${{ github.repository_owner == 'armbiankappa' }}
    uses: armbian/scripts/.github/workflows/build-images.yml@main
    with:

      config: "${{ github.event.client_payload.config || 'all.conf' }}"
      release: "${{ github.event.client_payload.release || 'nightly' }}"
      board: "${{ github.event.client_payload.board }}"
      parallel: 20
      part: 5
      of: 6
      version: "${{ needs.Prepare.outputs.version }}"
      deploy: true
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      KEY_ARMBIAN_UPLOAD: ${{ secrets.KEY_ARMBIAN_UPLOAD }}
      KNOWN_HOSTS_ARMBIAN_UPLOAD: ${{ secrets.KNOWN_HOSTS_ARMBIAN_UPLOAD }}
      ARMBIAN_HOST_UPLOAD: ${{ secrets.ARMBIAN_HOST_UPLOAD }}
      GPG_KEY1: ${{ secrets.GPG_KEY1 }}
      GPG_PASSPHRASE1: ${{ secrets.GPG_PASSPHRASE1 }}
